/*
  What: This is used to create the connection the mysql database
  Who: Wong Wing Yan 1155125194
  Where: backend mysql database connection
  Why: We need to first create connection when accessing the database
  How: use typeorm to create connection
*/
// the following content are generated by the typeorm autoinit
import "reflect-metadata";
import {createConnection} from "typeorm";
import {User} from "./entity/User";
//testing function for the connection
createConnection().then(async connection => {
       
    console.log("Inserting a new user into the database...");
    const user = new User();
    user.firstName = "Timber";
    user.lastName = "Saw";
    user.age = 25;
    await connection.manager.save(user);
    console.log("Saved a new user with id: " + user.id);

    console.log("Loading users from the database...");
    const users = await connection.manager.find(User);
    console.log("Loaded users: ", users);
    //test statement to show success
    console.log("Here you can setup and run express/koa/any other framework.");

}).catch(error => console.log(error));
